[window]
decorations = "Full"
startup_mode = "Maximized"
[font]
size = 14
  [font.normal]
    family = "Delugia Mono"  # Replace with your desired font family
    style = "Regular"
  [font.bold]
    family = "Delugia Mono"
    style = "Bold"
  [font.italic]
    family = "Delugia Mono"
    style = "Italic"
[scrolling]
  history = 100000

